---
- hosts: all
  tasks:
    - name: (copy) Copies files to remote locations
      copy:
        src: sample-file
        remote_src: no
        # content: ""
        # content: |
        dest: /tmp/file
        backup: yes

        owner: root
        group: root
        mode: 0644

      # Read the related documentation: playbooks_delegation.rst
      # run_once: yes
      # delegate_to: localhost
      # register: result
      # serial: 1
      # serial:
      #   - 1
      #   - 2
      #   - 3
      #   - 10%
      # local_action: |
      #   wait_for host={{ ansible_default_ipv4.address }}
      #   port={{ hostvars[inventory_hostname]['ansible_ssh_port'] | default('22') }}
      #   state=started
      #   timeout=300
      #   delay=60